name: 'Run PHP tests on changed files'
description: 'Run only changed PHP unit test files using Paratest'
branding:
  icon: 'filter'
  color: 'green'
inputs:
  branch-name:
    description: 'Name of branch to scan for last successful workflow run. Defaults to current branch.'
  workflow-id:
    description: 'Name of workflow to check for success. Defaults to current workflow.'
  tests-directory:
    description: 'The directory where the tests are located relative to the root. Defaults to tests.'
    default: tests
  ignore-paths:
    description: 'Files to ignore when determining which files to run.'
    default: 'vendor,node_modules,_ide_helper.php'
  list-only:
    description: 'List the files that would be run and exit, allowing you to bring your own test runner.'
    default: false
  separator:
    description: 'Separator to use when listing files. For use alongside the list-only option'
    default: ','
  allow-missing:
    description: 'Allow references to namespaces that cannot be found in the repository. When false an error will be thrown.'
    default: true
outputs:
  files: 
    description: A list of files that have changed since the last successful workflow run.
    value: ${{ steps.listChanged.outputs.files }}
runs:
  using: composite
  steps:
    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v6

    - name: Get last successful commit
      uses: nrwl/nx-set-shas@v3
      id: last_successful_commit
      with:
        main-branch-name: ${{ inputs.branch-name || steps.branch-name.outputs.current_branch }}
        workflow-id: ${{ inputs.workflow-id }}
        error-on-no-successful-workflow: false

    - name: Run changed-files with the commit of the last successful test workflow run
      id: changes_since_successful_commit
      uses: tj-actions/changed-files@v35
      with:
        files: '**.php'
        base_sha: ${{ steps.last_successful_commit.outputs.base }}
        separator: ','

    - name: Install php deps
      shell: bash
      run: |
        cd ${{ github.action_path }}
        composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

    - name: Change directory back to workspace
      shell: bash
      run: |
        cd ${{ github.workspace }}

    - name: List changed files
      id: listChanged
      if: ${{ inputs.list-only }}
      shell: bash
      run: |
        FILES=$(${{ github.action_path }}/bin/list-only-changed ${{ inputs.allow-missing && '--allow-missing' }} --ignore=${{ inputs.ignore-paths }} --tests-directory=${{ inputs.tests-directory }} --changed-files=${{ steps.changes_since_successful_commit.outputs.all_changed_and_modified_files }} --separator={{ inputs.separator }})
        echo "files=$FILES" >> "$GITHUB_OUTPUT"

    - name: Run paratest on changed files
      if: ${{ !inputs.list-only }}
      shell: bash
      run: ${{ github.action_path }}/bin/test-only-changed ${{ inputs.allow-missing && '--allow-missing' }} --ignore=${{ inputs.ignore-paths }} --tests-directory=${{ inputs.tests-directory }} --changed-files=${{ steps.changes_since_successful_commit.outputs.all_changed_and_modified_files }}